### ISSUE TITLE
Get everyone signed up for Github

### ISSUE THREAD

**Issue by theochemel** [Tartan-AUV/TAUV-ROS-Packages#87]
Invite:
- [x] Sarah - skfisher@andrew.cmu.edu
- [x] Nader - ndaruval@andrew.cmu.edu
- [x] John - jhduncan@andrew.cmu.edu
- [x] Rylan - rjmorgan@andrew.cmu.edu
- [x] Ayush - ayushshe@andrew.cmu.edu
- [x] Petros - pemmanou@andrew.cmu.edu
- [x] Arnav - arnavsab@andrew.cmu.edu
- [x] Cole - cherber@andrew.cmu.edu
- [x] TJ - tbridges@andrew.cmu.edu
- [x] Harrison - hwisebla@andrew.cmu.edu
- [x] Colm - crbarry@andrew.cmu.edu
- [x] Hank - uuuuuuxuninghua@gmail.com
- [x] Ronnie - tamarali@andrew.cmu.edu
- [x] Viktor - vzayakov@andrew.cmu.edu
- [x] Gleb - glebryabtsev@cmu.edu
- [x] Yiming - yimingf@andrew.cmu.edu
- [x] Alex Blass - ablass@andrew.cmu.edu

**Comment by colmrobarry** [comment]
Colm Barry

**Comment by GlebRyabtsev** [comment]
Gleb

**Comment by vzayakov** [comment]
Victor

**Comment by rjmorgan11** [comment]
Rylan

**Comment by sarahfi2her** [comment]
Sarah 😝

**Comment by yiming-f** [comment]
Yiming

**Comment by hankxu1212** [comment]
hank

**Comment by TheronAma** [comment]
Ronnie

**Comment by ndaruvala** [comment]
Nader

**Comment by ayush-shekhar01** [comment]
Ayush

**Comment by Petros-Emmanouilidis** [comment]
Petros

**Comment by ColeHerber** [comment]
Cole

**Comment by Tj-Bridge** [comment]
Tj

**Comment by harrison6462** [comment]
Harrison

**Comment by a26blass** [comment]
Alex B

**Comment by Arnav-99** [comment]
Arnav Sabharwal

**Comment by evelynmiller03** [comment]
Evelyn Miller
